Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "pathgrant"
  config.vm.box_check_update = true

  config.vm.hostname = "pathgrant.local"

  config.vm.provider "vmware_desktop" do |vm|
    # gui = true
    vm.vmx["memsize"] = "4096"
    vm.vmx["numvcpus"] = "2"
  end

  # Add WireGuard
  config.vm.provision :shell, inline: "sudo apt install --yes wireguard"
end
